name: test-pavu
base: core18
version: '0.1'
summary: pavu that works with test-qt-platform
description: |
  pavucontrol, qt version, that works with test-qt-platform and mir-kiosk wayland

grade: stable
confinement: strict

plugs:
  network:
  opengl:
  wayland:
  # the following provided by test-qt-platform
  qt-platform:
    interface: content
    content: qt-platform
    target: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET
  fonts-etc:
    interface: content
    content: fonts
    target: $SNAP_DATA/etc/fonts
  fonts:
    interface: content
    content: fonts-usr-share
    target: $SNAP/usr/share/fonts
  glvnd:
    interface: content
    content: glvnd
    target: $SNAP/usr/share/glvnd

layout:
  /etc/glvnd:
    bind: $SNAP/etc/glvnd
  /usr/share/X11/xkb:
    bind: $SNAP/usr/share/X11/xkb
  /usr/share/fonts:
    bind: $SNAP/usr/share/fonts
  /usr/local/share/fonts:
    bind: $SNAP/usr/local/share/fonts
  /usr/share/glvnd:
    bind: $SNAP/usr/share/glvnd
  /usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/qt5:
    bind: $SNAP/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/qt5
  /usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/dri:
    bind: $SNAP/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/dri

apps:
  pavucontrol:
    command: bin/wayland-launch $SNAP/bin/pavucontrol-qt
    plugs: [ wayland, opengl, audio-playback, audio-record ]

environment:
    QT_QPA_PLATFORM: wayland
    FONTCONFIG_FILE: $SNAP_DATA/etc/fonts/fonts.conf
    FONTCONFIG_PATH: $SNAP_DATA/etc/fonts
    FONTCONFIG_FILE: $SNAP_DATA/etc/fonts/fonts.conf
    FONTCONFIG_PATH: $SNAP_DATA/etc/fonts
    LIBGL_DRIVERS_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/dri
    # find EGL from content provider (https://www.mesa3d.org/egl.html
    __EGL_VENDOR_LIBRARY_DIRS: $SNAP/etc/glvnd/egl_vendor.d:$SNAP/usr/share/glvnd/egl_vendor.d
    LD_LIBRARY_PATH: ${LD_LIBRARY_PATH}:${SNAP}/usr/lib/arm-linux-gnueabihf/

parts:
  pavucontrol:
    plugin: cmake
    source: https://git.launchpad.net/ubuntu/+source/pavucontrol-qt
    source-branch: applied/ubuntu/bionic
    source-type: git
    build-environment:
    - DCMAKE_INSTALL_PREFIX: $SNAP
    build-packages:
      - build-essential
    stage-packages:
      - libqt5widgets5
      - qttools5-dev
      - qtbase5-dev
      - lxqt-build-tools
      - libpulse-dev 
  mir-kiosk-snap-launch:
    plugin: dump
    source: https://github.com/MirServer/mir-kiosk-snap-launch.git
    override-build:  $SNAPCRAFT_PART_BUILD/build-with-plugs.sh opengl wayland

  deps:
    plugin: nil
    stage-packages:
      - libatkmm-1.6-1v5
      - libcanberra-gtk3-0
      - libcanberra0
      - libglib2.0-0
      - libglibmm-2.4-1v5
      - libgtk-3-0
      - libgtkmm-3.0-1v5
      - libpulse-mainloop-glib0
      - libpulse0
